import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import type { Metadata } from "next";
import { League_Gothic, Mulish } from "next/font/google";
import "./globals.css";
import { ClientProviders } from "./clientProviders";
import NavBar from "../components/NavBar";

const leagueGothic = League_Gothic({
  weight: "400",
  style: "normal",
  variable: "--font-leagotic",
  subsets: [],
});

const mulish = Mulish({
  weight: ["200", "500", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-mulish",
  subsets: [],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={`${leagueGothic.variable} ${mulish.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <NavBar />
          <ClientProviders>{children}</ClientProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
